name: oops
description: 一个提供链式调用语法糖的Flutter库，用于减少嵌套层级和代码量
version: 0.1.0
homepage: https://github.com/yourusername/oops

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
